name: CD

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force container rebuild'
        required: true
        type: choice
        options: [yes, no]

jobs:
  Alpine:
    name: Alpine
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ '3.11', '3.12', '3.13', '3.14', '3.15' ]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build context
        id: build_context
        run: |
          dockerfile=$(echo "${{matrix.version}}" | tr -d ".")
          echo "::set-output name=dockerfile::$dockerfile.docker"

      - name: Check for rebuild
        id: update_check
        continue-on-error: true
        run : |
          # [update-check]

          echo -e "::group::\033[34mChecking for packages updates…\033[0m"

          if [[ "${{ github.event.inputs.force_rebuild }}" == "true" ]] ; then
            echo "::warning::Rebuild ${{matrix.version}} (reason: forced rebuild)"
            exit 1
          else
            docker run --rm essentialkaos/alpine:${{matrix.version}} checkupdate

            if [[ $? -ne 0 ]] ; then
              echo "::warning::Rebuild ${{matrix.version}} (reason: packages update)"
              exit 1
            fi
          fi

          echo "::endgroup::"

          echo -e "::group::\033[34mChecking for rebuilt base image…\033[0m"

          docker pull alpine:${{matrix.version}}

          orig_dig=$(docker inspect "alpine:${{matrix.version}}" | jq -r '.[0].RootFS.Layers[0]')
          our_dig=$(docker inspect "essentialkaos/alpine:${{matrix.version}}" | jq -r '.[0].RootFS.Layers[0]')

          echo ""
          echo "Original: ${orig_dig}"
          echo "Our:      ${our_dig}"

          if [[ "$orig_dig" != "$our_dig" ]] ; then
            echo "::warning::Rebuild ${{matrix.version}} (reason: rebuilt base image)"
            exit 1
          fi

          echo "::endgroup::"

      - name: Rebuild and push image
        if: ${{ steps.update_check.outcome == 'failure' }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ steps.build_context.outputs.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{github.repository}}:${{matrix.version}}
            ${{github.repository}}:${{matrix.version}}

      - name: Show info about images
        uses: essentialkaos/docker-info-action@v1
        with:
          image: alpine:${{matrix.version}} essentialkaos/alpine:${{matrix.version}}
