name: CD

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 4 * * *'

jobs:
  Alpine:
    name: Alpine
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ '3.11', '3.12', '3.13', '3.14' ]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for updates
        id: update_check
        continue-on-error: true
        run : |
          docker run --rm essentialkaos/alpine:${{ matrix.version }} checkupdate

      - name: Trigger image rebuild
        if: ${{ steps.update_check.outcome == 'failure' }}
        run: |
          curl -H "Content-Type: application/json" --data '{"docker_tag": "${{ matrix.version }}"}' -X POST ${{ secrets.BUILD_TRIGGER_URL }}

      - name: Check for rebuilt base image
        if: ${{ steps.update_check.outcome != 'failure' }}
        run: |
          echo "::group::Fetching images…"
          docker pull alpine:${{ matrix.version }}
          docker pull essentialkaos/alpine:${{ matrix.version }}

          orig_dig=$(docker inspect "alpine:${{ matrix.version }}" | jq -r '.[0].RootFS.Layers[0]')
          our_dig=$(docker inspect "essentialkaos/alpine:${{ matrix.version }}" | jq -r '.[0].RootFS.Layers[0]')

          echo "::endgroup::"

          if [[ "$orig_dig" != "$our_dig" ]] ; then
            echo "Base image was updated! Sending request to DockerHub for rebuilding ${{ matrix.version }}"
            curl -H "Content-Type: application/json" --data '{"docker_tag": "${{ matrix.version }}"}' -X POST ${{ secrets.BUILD_TRIGGER_URL }}
          else
            echo "No base image updates"
          fi
